### ISSUE TITLE
runtime exception

### ISSUE THREAD

**Issue by makemoneystuff** [bOmBeLq/Ponzi#2]
Hi, i installed it and works fine.

But i had a problem, i dont know to change the url  from 127.0.0.1 to http://mydomaina.com.

Example how i can change this:
Payout address
xxxxxxxxx
Referrer link http://127.0.0.1:8000/?ref=1 

to
Payout address
xxxxxxxxx
Referrer link http://mydomain.com/?ref=1 

thanks, will buy btc to make a donation, your script is very good.

**Comment by bOmBeLq** [comment]
I assume You have purchased and attached domain to Your server?

**Comment by makemoneystuff** [comment]
Hi, i done it. i should work on web folder :) i start learn composer and symfony yesterday. i make all day learning about it only to use the script :). Thanks for nice script its working now. Will fund my btc to sent some donation. Thanks
